/* The following code was generated by JFlex 1.6.0 */

package IC.Parser;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>E:/TAU/Year3/workspace/Compiler_EX1/src/ic.lex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\50\1\40"+
    "\2\0\1\53\1\57\1\0\1\41\1\42\1\5\1\51\1\37\1\52"+
    "\1\47\1\4\1\10\11\11\1\0\1\36\1\54\1\56\1\55\2\0"+
    "\32\7\1\43\1\61\1\44\3\0\1\14\1\26\1\12\1\22\1\16"+
    "\1\32\1\30\1\34\1\23\1\6\1\35\1\13\1\6\1\21\1\25"+
    "\2\6\1\27\1\15\1\20\1\31\1\24\1\33\1\17\2\6\1\45"+
    "\1\60\1\46\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\6\2\7"+
    "\14\5\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\2\1\1\31\1\32\1\33\1\2\1\0"+
    "\13\5\1\34\6\5\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\2\0\11\5\1\47"+
    "\1\5\1\50\6\5\1\0\1\2\5\5\1\51\1\5"+
    "\1\52\1\53\1\54\1\55\5\5\1\56\6\5\1\57"+
    "\1\5\1\60\1\61\1\5\1\62\1\63\1\64\2\5"+
    "\1\65\1\5\1\66\1\67\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\144\0\310\0\144\0\372"+
    "\0\u012c\0\144\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258"+
    "\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\144"+
    "\0\144\0\144\0\144\0\144\0\144\0\144\0\144\0\144"+
    "\0\144\0\u03e8\0\144\0\144\0\144\0\u041a\0\u044c\0\u047e"+
    "\0\u04b0\0\u04e2\0\u0514\0\144\0\u0546\0\u0578\0\u05aa\0\u05dc"+
    "\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6\0\u0708\0\u073a\0\u076c"+
    "\0\u079e\0\u07d0\0\372\0\u0802\0\u0834\0\u0866\0\u0898\0\u08ca"+
    "\0\u08fc\0\144\0\144\0\144\0\144\0\144\0\144\0\144"+
    "\0\144\0\144\0\144\0\u092e\0\u0960\0\u0992\0\u09c4\0\u09f6"+
    "\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22\0\372\0\u0b54"+
    "\0\372\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2"+
    "\0\u092e\0\u0ce4\0\u0d16\0\u0d48\0\u0d7a\0\u0dac\0\372\0\u0dde"+
    "\0\372\0\372\0\372\0\372\0\u0e10\0\u0e42\0\u0e74\0\u0ea6"+
    "\0\u0ed8\0\372\0\u0f0a\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\u1004"+
    "\0\372\0\u1036\0\372\0\372\0\u1068\0\372\0\372\0\372"+
    "\0\u109a\0\u10cc\0\372\0\u10fe\0\372\0\372\0\372";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\10\1\16\1\17\1\10\1\20"+
    "\1\21\1\10\1\22\1\23\1\10\1\24\1\25\2\10"+
    "\1\26\1\27\2\10\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\3\1\53"+
    "\2\3\35\53\1\54\20\53\1\55\64\0\1\5\63\0"+
    "\1\56\1\57\62\0\30\10\32\0\30\11\34\0\2\13"+
    "\56\0\5\10\1\60\11\10\1\61\10\10\32\0\10\10"+
    "\1\62\17\10\32\0\12\10\1\63\15\10\32\0\5\10"+
    "\1\64\3\10\1\65\16\10\32\0\21\10\1\66\4\10"+
    "\1\67\1\10\32\0\10\10\1\70\12\10\1\71\4\10"+
    "\32\0\13\10\1\72\10\10\1\73\3\10\32\0\17\10"+
    "\1\74\10\10\32\0\17\10\1\75\1\10\1\76\6\10"+
    "\32\0\10\10\1\77\17\10\32\0\6\10\1\100\21\10"+
    "\32\0\26\10\1\101\1\10\102\0\1\102\61\0\1\103"+
    "\61\0\1\104\61\0\1\105\62\0\1\106\62\0\1\107"+
    "\1\0\1\53\2\0\35\53\1\0\20\53\21\0\1\110"+
    "\1\111\5\0\1\112\10\0\1\113\21\0\1\56\1\4"+
    "\1\5\57\56\5\114\1\115\54\114\6\0\6\10\1\116"+
    "\21\10\32\0\13\10\1\117\14\10\32\0\13\10\1\120"+
    "\14\10\32\0\6\10\1\121\12\10\1\122\6\10\32\0"+
    "\7\10\1\123\20\10\32\0\12\10\1\124\15\10\32\0"+
    "\23\10\1\125\4\10\32\0\15\10\1\126\12\10\32\0"+
    "\25\10\1\127\2\10\32\0\5\10\1\130\22\10\32\0"+
    "\12\10\1\131\15\10\32\0\15\10\1\132\12\10\32\0"+
    "\17\10\1\133\10\10\32\0\10\10\1\134\17\10\32\0"+
    "\12\10\1\135\15\10\32\0\5\10\1\136\22\10\32\0"+
    "\15\10\1\137\12\10\24\0\5\114\1\140\60\114\1\141"+
    "\1\140\54\114\6\0\7\10\1\142\20\10\32\0\12\10"+
    "\1\143\15\10\32\0\22\10\1\144\5\10\32\0\12\10"+
    "\1\145\15\10\32\0\15\10\1\146\12\10\32\0\10\10"+
    "\1\147\17\10\32\0\10\10\1\150\17\10\32\0\10\10"+
    "\1\151\17\10\32\0\7\10\1\152\20\10\32\0\5\10"+
    "\1\153\22\10\32\0\14\10\1\154\13\10\32\0\5\10"+
    "\1\155\22\10\32\0\6\10\1\156\21\10\32\0\23\10"+
    "\1\157\4\10\32\0\7\10\1\160\20\10\32\0\5\10"+
    "\1\161\22\10\24\0\4\114\1\5\1\140\54\114\6\0"+
    "\7\10\1\162\20\10\32\0\15\10\1\163\12\10\32\0"+
    "\12\10\1\164\15\10\32\0\15\10\1\165\12\10\32\0"+
    "\13\10\1\166\14\10\32\0\13\10\1\167\14\10\32\0"+
    "\10\10\1\170\17\10\32\0\27\10\1\171\32\0\21\10"+
    "\1\172\6\10\32\0\10\10\1\173\17\10\32\0\10\10"+
    "\1\174\17\10\32\0\13\10\1\175\14\10\32\0\26\10"+
    "\1\176\1\10\32\0\4\10\1\177\23\10\32\0\22\10"+
    "\1\200\5\10\32\0\14\10\1\201\13\10\32\0\6\10"+
    "\1\202\21\10\32\0\13\10\1\203\14\10\32\0\23\10"+
    "\1\204\4\10\32\0\7\10\1\205\20\10\32\0\13\10"+
    "\1\206\14\10\32\0\10\10\1\207\17\10\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4400];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\1\11\2\1\1\11"+
    "\15\1\12\11\1\1\3\11\6\1\1\11\2\1\1\0"+
    "\22\1\12\11\2\0\22\1\1\0\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer string = new StringBuffer();

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }
  
  private Symbol stringSymbol(int type, String value) {
	return new Symbol(type, yyline+1, yycolumn+2-value.length(), value);
  }
  


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new LexicalError(yytext(), yyline+1, yycolumn+1);
          }
        case 57: break;
        case 2: 
          { /* ignore */
          }
        case 58: break;
        case 3: 
          { return symbol(sym.DIVIDE, yytext());
          }
        case 59: break;
        case 4: 
          { return symbol(sym.MULT, yytext());
          }
        case 60: break;
        case 5: 
          { return symbol(sym.ID, yytext());
          }
        case 61: break;
        case 6: 
          { return symbol(sym.CLASS_ID, yytext());
          }
        case 62: break;
        case 7: 
          { return symbol(sym.INTEGER_LITERAL, yytext());
          }
        case 63: break;
        case 8: 
          { return symbol(sym.SEMICOLON, yytext());
          }
        case 64: break;
        case 9: 
          { return symbol(sym.COMMA, yytext());
          }
        case 65: break;
        case 10: 
          { string.setLength(0); string.append("\""); yybegin(STRING);
          }
        case 66: break;
        case 11: 
          { return symbol(sym.LP, yytext());
          }
        case 67: break;
        case 12: 
          { return symbol(sym.RP, yytext());
          }
        case 68: break;
        case 13: 
          { return symbol(sym.LC, yytext());
          }
        case 69: break;
        case 14: 
          { return symbol(sym.RC, yytext());
          }
        case 70: break;
        case 15: 
          { return symbol(sym.LB, yytext());
          }
        case 71: break;
        case 16: 
          { return symbol(sym.RB, yytext());
          }
        case 72: break;
        case 17: 
          { return symbol(sym.DOT, yytext());
          }
        case 73: break;
        case 18: 
          { return symbol(sym.EXCLAMATION_MARK, yytext());
          }
        case 74: break;
        case 19: 
          { return symbol(sym.PLUS, yytext());
          }
        case 75: break;
        case 20: 
          { return symbol(sym.MINUS, yytext());
          }
        case 76: break;
        case 21: 
          { return symbol(sym.REMINDER, yytext());
          }
        case 77: break;
        case 22: 
          { return symbol(sym.SMALLER_OP, yytext());
          }
        case 78: break;
        case 23: 
          { return symbol(sym.LARGER_OP, yytext());
          }
        case 79: break;
        case 24: 
          { return symbol(sym.ASSIGN, yytext());
          }
        case 80: break;
        case 25: 
          { string.append( yytext() );
          }
        case 81: break;
        case 26: 
          { yybegin(YYINITIAL); 
								   string.append("\"");
                                   return stringSymbol(sym.STRING_LITERAL, 
                                   string.toString());
          }
        case 82: break;
        case 27: 
          { string.append('\\');
          }
        case 83: break;
        case 28: 
          { return symbol(sym.IF_KEYWORD, yytext());
          }
        case 84: break;
        case 29: 
          { return symbol(sym.NOT_EQUALS_OP, yytext());
          }
        case 85: break;
        case 30: 
          { return symbol(sym.SMALLER_EQ_OP, yytext());
          }
        case 86: break;
        case 31: 
          { return symbol(sym.LARGER_EQ_OP, yytext());
          }
        case 87: break;
        case 32: 
          { return symbol(sym.EQUALS_OP, yytext());
          }
        case 88: break;
        case 33: 
          { return symbol(sym.AND_OP, yytext());
          }
        case 89: break;
        case 34: 
          { return symbol(sym.OR_OP, yytext());
          }
        case 90: break;
        case 35: 
          { string.append('\t');
          }
        case 91: break;
        case 36: 
          { string.append("\\n");
          }
        case 92: break;
        case 37: 
          { string.append('\r');
          }
        case 93: break;
        case 38: 
          { string.append("\\\"");
          }
        case 94: break;
        case 39: 
          { return symbol(sym.NEW_KEYWORD, yytext());
          }
        case 95: break;
        case 40: 
          { return symbol(sym.INT_KEYWORD, yytext());
          }
        case 96: break;
        case 41: 
          { return symbol(sym.ELSE_KEYWORD, yytext());
          }
        case 97: break;
        case 42: 
          { return symbol(sym.TRUE_LITERAL, yytext());
          }
        case 98: break;
        case 43: 
          { return symbol(sym.THIS_KEYWORD, yytext());
          }
        case 99: break;
        case 44: 
          { return symbol(sym.NULL_LITERAL, yytext());
          }
        case 100: break;
        case 45: 
          { return symbol(sym.VOID_KEYWORD, yytext());
          }
        case 101: break;
        case 46: 
          { return symbol(sym.CLASS_KEYWORD, yytext());
          }
        case 102: break;
        case 47: 
          { return symbol(sym.BREAK_KEYWORD, yytext());
          }
        case 103: break;
        case 48: 
          { return symbol(sym.FALSE_LITERAL, yytext());
          }
        case 104: break;
        case 49: 
          { return symbol(sym.WHILE_KEYWORD, yytext());
          }
        case 105: break;
        case 50: 
          { return symbol(sym.LENGTH_KEYWORD, yytext());
          }
        case 106: break;
        case 51: 
          { return symbol(sym.STATIC_KEYWORD, yytext());
          }
        case 107: break;
        case 52: 
          { return symbol(sym.STRING_KEYWORD, yytext());
          }
        case 108: break;
        case 53: 
          { return symbol(sym.RETURN_KEYWORD, yytext());
          }
        case 109: break;
        case 54: 
          { return symbol(sym.EXTENDS_KEYWORD, yytext());
          }
        case 110: break;
        case 55: 
          { return symbol(sym.BOOLEAN_KEYWORD, yytext());
          }
        case 111: break;
        case 56: 
          { return symbol(sym.CONTINUE_KEYWORD, yytext());
          }
        case 112: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
